import { resolve } from "node:path"

export const APP_ROOT = resolve(import.meta.dirname, "../..")
export const STAGE_ROOT = resolve(APP_ROOT, ".ondo-b-standalone")
export const STAGE_DIST = resolve(STAGE_ROOT, "dist")
export const LOCAL_ONLY_PROJECT_ID = "appgprj_local_only_ondo_b_artifact"
export const HISTORICAL_B_PROJECT_ID = "appgprj_6a85de65d6148191aa042ae9c2787dd2"
export const PERSONAL_DEPLOY_OWNER = "woogieboogie-jl"
export const PERSONAL_VERCEL_USER = "jaewook-9643"
// The one Vercel destination explicitly approved for this product. Vercel
// represents a personal account's project collection with a `team_*` orgId,
// so all three linked-project fields are pinned instead of inferring ownership
// from the orgId prefix.
export const PERSONAL_VERCEL_PROJECT_ID = "prj_w5rckTz9B1DO55fvVRXjQRy9L5RM"
export const PERSONAL_VERCEL_ORG_ID = "team_6kJAloQ9WlswvMtbbCmGI7Er"
export const PERSONAL_VERCEL_PROJECT_NAME = "ondo"
export const LEGACY_DISCOVERY_QUERY_KEYS = Object.freeze([
  "category",
  "city",
  "detail",
  "editorialPlaceId",
  "q",
  "venueId",
  "view",
])

// These modules are intentionally B-native: they implement truthful,
// synchronous device-local walkthroughs and do not import the legacy provider,
// KYC, wallet, chain, or mock-product graph.
export const B_NATIVE_INTERACTIVE_FILES = Object.freeze([
  "features/ondo/contracts/execution-mode.ts",
  "features/ondo/contracts/sample-environment.ts",
  "features/ondo/contracts/kpass-capabilities.ts",
  "features/ondo/contracts/identity-journey-samples.ts",
  "features/ondo/contracts/temperature-timeline.ts",
  "features/ondo/after19/after19-global-b-model.ts",
  "features/ondo/after19/after19-guest-memory-b.ts",
  "features/ondo/after19/after19-global-b.tsx",
  "features/ondo/after19/after19-global-b.module.css",
  "features/ondo/after19/after19-place-return-b-model.ts",
  "features/ondo/identity-b/account-save-gate-b.tsx",
  "features/ondo/identity-b/account-save-gate-b.module.css",
  "features/ondo/identity-b/action-gate-contract-b.ts",
  "features/ondo/identity-b/action-gate-coordinator-b.tsx",
  "features/ondo/identity-b/action-gate-coordinator-b.module.css",
  "features/ondo/identity-b/activity-profile-b-provider.tsx",
  "features/ondo/identity-b/profile-reputation-b.tsx",
  "features/ondo/identity-b/profile-reputation-b.module.css",
  "features/ondo/identity-b/local-check-walkthrough-b.tsx",
  "features/ondo/identity-b/local-check-walkthrough-b.module.css",
  "features/ondo/identity-b/traveler-id-entry-b.tsx",
  "features/ondo/identity-b/traveler-id-entry-b.module.css",
  "features/ondo/identity-b/journey-stamps-b.tsx",
  "features/ondo/identity-b/journey-stamps-b.module.css",
  "features/ondo/identity-b/journey-stamps-navigation-b.ts",
  "features/ondo/identity-b/traveler-id-status-b.ts",
  "features/ondo/identity-b/ktour-id-setup-b.tsx",
  "features/ondo/identity-b/ktour-id-setup-b.module.css",
  "features/ondo/identity-b/ktour-id-setup-model-b.ts",
  "features/ondo/shared/ui/ktour-id-mark.tsx",
  "features/ondo/identity-b/kpass-decision-copy.ts",
  "features/ondo/identity-b/kpass-service-card-b.tsx",
  "features/ondo/identity-b/kpass-service-card-b.module.css",
  "features/ondo/identity-b/passport-ocr-step-b.tsx",
  "features/ondo/identity-b/passport-ocr-step-b.module.css",
  "features/ondo/map/place-return-ui-snapshot-b.ts",
  "features/ondo/map/temperature-timeline-b.tsx",
  "features/ondo/map/temperature-timeline-b.module.css",
  "features/ondo/map/sample-temperature-presentation-b.ts",
  "features/ondo/map/sample-activity-meter-b.tsx",
  "features/ondo/map/sample-activity-meter-b.module.css",
  "features/ondo/contracts/traveler-activity-b.ts",
  "features/ondo/map/food-photo-b.tsx",
  "features/ondo/map/food-photo-b.module.css",
  "features/ondo/map/traveler-activity-map-b.tsx",
  "features/ondo/map/traveler-activity-map-b.module.css",
  "features/ondo/map/researched-food-b.ts",
  "features/ondo/map/researched-food-panel-b.tsx",
  "features/ondo/map/researched-food-panel-b.module.css",
  "features/ondo/map/map-balance-entry-b.tsx",
  "features/ondo/map/map-balance-entry-b.module.css",
  "features/ondo/map/place-service-map-return-b.ts",
  "features/ondo/place/place-service-actions-b.tsx",
  "features/ondo/place/place-service-actions-b.module.css",
  "features/ondo/experience-b/experience-model-b.ts",
  "features/ondo/experience-b/experience-store-b.ts",
  "features/ondo/experience-b/experience-copy-b.ts",
  "features/ondo/experience-b/experience-b.tsx",
  "features/ondo/experience-b/saved-experience-b.tsx",
  "features/ondo/experience-b/experience-b.module.css",
  "data/ondo/research/seoul-food-pulse.json",
  "data/ondo/research/busan-food-pulse.json",
  "data/ondo/research/jeju-food-pulse.json",
  "features/ondo/shared/ui/sample-info-button-b.tsx",
  "features/ondo/shared/ui/sample-info-button-b.module.css",
  "features/ondo/integration-demo-b/integration-demo-model-b.ts",
  "features/ondo/integration-demo-b/integration-demo-b.tsx",
  "features/ondo/integration-demo-b/integration-demo-b.module.css",
  "features/ondo/reservation-b/reservation-model-b.ts",
  "features/ondo/reservation-b/reservation-copy-b.ts",
  "features/ondo/reservation-b/reservation-b.tsx",
  "features/ondo/reservation-b/reservation-b.module.css",
  "features/ondo/settings/account-services-sample-b.tsx",
  "features/ondo/settings/account-services-sample-model-b.ts",
  "features/ondo/settings/account-services-sample-b.module.css",
  "features/ondo/local-signal-b/local-signal-layer-b.tsx",
  "features/ondo/local-signal-b/local-signal-layer-b.module.css",
  "features/ondo/local-signal-b/local-signal-model-b.ts",
])

// Product-owned commerce walkthroughs are positively required. They are kept
// separate from the retired provider/checkout graph and cannot be omitted by a
// broad legacy scanner rule.
export const REQUIRED_B_NATIVE_COMMERCE_FILES = Object.freeze([
  "features/ondo/commerce-b/place-service-registry-b.ts",
  "features/ondo/commerce-b/stable-commerce-model-b.ts",
  "features/ondo/commerce-b/funding-rail-model-b.ts",
  "features/ondo/commerce-b/funding-rail-b.module.css",
  "features/ondo/commerce-b/stablecoin-funding-b.tsx",
  "features/ondo/commerce-b/stablecoin-funding-b.module.css",
  "features/ondo/commerce-b/id-wallet-commerce-b.tsx",
  "features/ondo/commerce-b/id-wallet-commerce-b.module.css",
  "features/ondo/commerce-b/commerce-refunds-b.tsx",
  "features/ondo/commerce-b/commerce-sample-response-b.ts",
  "features/ondo/commerce-b/commerce-operations-b.module.css",
  "features/ondo/commerce-b/visit-stamp-receipt-b.tsx",
  "features/ondo/commerce-b/visit-stamp-receipt-b.module.css",
  "features/ondo/commerce-b/journey-visit-b.tsx",
  "features/ondo/commerce-b/journey-visit-b.module.css",
])

// Labs is a product-owned, deterministic technical preview. The standalone
// preparation keeps only its B adapter so the legacy OndoProvider graph never
// crosses the isolated artifact boundary.
export const REQUIRED_B_NATIVE_LABS_FILES = Object.freeze([
  "features/ondo/contracts/commerce.ts",
  "features/ondo/contracts/domain.ts",
  "features/ondo/contracts/evidence.ts",
  "features/ondo/labs/labs-entry.tsx",
  "features/ondo/labs/labs-review-truth-b.ts",
  "features/ondo/labs/labs-model.ts",
  "features/ondo/labs/labs.module.css",
  "features/ondo/shared/ui/sheet-b.tsx",
  "features/ondo/shared/ui/ui.module.css",
  "features/ondo/shared/ui/modal-layer-priority.ts",
  "features/ondo/shared/ui/use-sheet-presence.ts",
  "features/ondo/shared/ui/use-qa-controls.ts",
])

export const SOURCE_FILES = Object.freeze([
  "features/ondo/commerce-b/wallet-connection-preview-b.tsx",
  "features/ondo/identity-b/identity-demo-boundary-b.ts",
  "features/ondo/identity-b/identity-handoff-step-b.tsx",
  "features/ondo/identity-b/identity-holder-step-b.tsx",
  "features/ondo/identity-b/passport-face-step-b.tsx",
  "features/ondo/integration-demo-b/partner-handoff-b.tsx",
  "app/page.tsx",
  "app/ondo-b/page.tsx",
  "app/api/ondo/venues/[venueId]/route.ts",
  "build/sites-vite-plugin.ts",
  "data/ondo-venues/canonical-venues.json",
  "data/ondo-venues/canonical-venues-map.json",
  "features/ondo/app/ondo-app-b.tsx",
  "features/ondo/app/ondo-product-b.tsx",
  "features/ondo/app/ondo-shell.module.css",
  "features/ondo/connect/table-model.ts",
  "features/ondo/connect/table-policy-b.ts",
  "features/ondo/connect/table-activity-b.ts",
  "features/ondo/connect/tables-entry-b.tsx",
  "features/ondo/connect/pulse-table-b.module.css",
  "features/ondo/contracts/return-to-b.ts",
  "features/ondo/contracts/return-to.ts",
  "features/ondo/contracts/return-to-integrity.ts",
  "features/ondo/map/b-discovery-history.ts",
  "features/ondo/map/b-discovery-focus.ts",
  "features/ondo/map/b-discovery-personalization.ts",
  "features/ondo/map/canonical-venue-capsule-b.module.css",
  "features/ondo/map/canonical-venue-capsule-b.tsx",
  "features/ondo/map/map-b.module.css",
  "features/ondo/map/map-entry-b.tsx",
  "features/ondo/map/map-options-b.tsx",
  "features/ondo/map/map-options-b.module.css",
  "features/ondo/map/japan-first-discovery-b.tsx",
  "features/ondo/map/japan-first-discovery-b.module.css",
  "features/ondo/my/private-note.tsx",
  "features/ondo/my/memory-venue-card-b-model.ts",
  "features/ondo/my/memory-venue-card-b.module.css",
  "features/ondo/my/memory-venue-card-b.tsx",
  "features/ondo/my/my-korea-model.ts",
  "features/ondo/my/my-korea-place-return-b.ts",
  "features/ondo/my/korea-memory-map-b.tsx",
  "features/ondo/my/korea-memory-map-b.module.css",
  "features/ondo/my/saved-entry-b.tsx",
  "features/ondo/my/saved-entry-b.module.css",
  "features/ondo/onboarding/official-directory-onboarding.tsx",
  "features/ondo/onboarding/official-directory-onboarding.module.css",
  "features/ondo/place/canonical-place-mount.tsx",
  "features/ondo/map/place-return-ui-snapshot-b.ts",
  "features/ondo/place/canonical-place-overlay.tsx",
  "features/ondo/place/canonical-place.module.css",
  "features/ondo/place/editorial-place-mount-b.tsx",
  "features/ondo/place/editorial-place-overlay-b.tsx",
  "features/ondo/place/editorial-place-overlay-b.module.css",
  "features/ondo/pulse-b/pulse-model-b.ts",
  "features/ondo/pulse-b/japan-first-pulse-model-b.ts",
  "features/ondo/settings/settings-entry-b.tsx",
  "features/ondo/settings/settings-entry-b.module.css",
  "features/ondo/settings/settings-model-b.ts",
  "features/ondo/shared/state/ondo-b-appearance.ts",
  "features/ondo/shared/state/ondo-b-preferences.ts",
  "features/ondo/shared/state/ondo-b-provider.tsx",
  "features/ondo/shared/state/ondo-b-window.d.ts",
  "features/ondo/shared/state/private-note-draft-memory.ts",
  "features/ondo/shared/time/product-timeline-b.ts",
  "features/ondo/shared/ui/focus-destination.ts",
  "features/ondo/shared/ui/is-rendered-focusable.ts",
  "features/ondo/shared/ui/ondo-brand-lockup-b.tsx",
  "features/ondo/shared/ui/ondo-brand-lockup-b.module.css",
  "features/ondo/shared/ui/production-local.module.css",
  "features/ondo/shared/ui/use-modal-isolation.ts",
  "lib/map/korea-atlas-data.ts",
  "lib/ondo/map/ondo-map-style.ts",
  "lib/ondo/venues/contracts.ts",
  "lib/ondo/venues/canonical-allowlist.ts",
  "lib/ondo/venues/detail-contract.ts",
  "lib/ondo/venues/detail-server.ts",
  "lib/ondo/venues/display.ts",
  "lib/ondo/venues/map-data.ts",
  "lib/ondo/venues/map-discovery-aliases.ts",
  ...B_NATIVE_INTERACTIVE_FILES,
  ...REQUIRED_B_NATIVE_COMMERCE_FILES,
  ...REQUIRED_B_NATIVE_LABS_FILES,
])

export const PUBLIC_FILES = Object.freeze([
  "public/editorial/food/perilla-noodles-illustration-v1.jpg",
  "public/media/venues/onion-anguk-christopher-phua-20250301.jpg",
  "public/media/venues/research-jeju-sinseoloreum/momguk-gong-seokbae-20190723-v1.jpg",
  "public/media/venues/research-seoul-hakrim-dabang/exterior-seefooddiet-20250110-v1.jpg",
  "public/editorial/food/tteokgalbi-illustration-v1.jpg",
  "public/editorial/food/coffee-croissant-illustration-v1.jpg",
  "public/og-ktour-korea-v3.png",
  "public/brand/ktour-id-mono-v1.svg",
  "public/brand/ktour-id-mono-v1-16.png",
  "public/brand/ktour-id-mono-v1-32.png",
  "public/brand/ktour-id-mono-v1-180.png",
  "public/brand/ktour-id-mono-v1-192.png",
  "public/brand/ktour-id-mono-v1-512.png",
  "public/editorial/food/ondo-category-casual-v1.jpg",
  "public/editorial/food/ondo-category-chinese-v1.jpg",
  "public/editorial/food/ondo-category-global-v1.jpg",
  "public/editorial/food/ondo-category-japanese-v1.jpg",
  "public/editorial/food/ondo-category-korean-v1.jpg",
  "public/editorial/food/ondo-category-night-v1.jpg",
  "public/editorial/food/ondo-category-night-v2.jpg",
  "public/editorial/food/ondo-category-night-v3.jpg",
  "public/editorial/food/ondo-category-specialty-v1.jpg",
  "public/editorial/people/ondo-my-korea-inspiration-v2-landscape.jpg",
  "public/editorial/people/ondo-onboarding-travelers-v2-landscape.jpg",
  "public/editorial/people/ondo-tables-dinner-v2-landscape.jpg",
  "public/editorial/japan-first-c01-sesame-oil.jpg",
  "public/editorial/japan-first-c03-seoul-eight-hours.jpg",
  "public/editorial/japan-first-c06-beauty-research.jpg",
  "public/editorial/japan-first-c18-jeju-screen-route.jpg",
  "public/editorial/japan-first-c20-jeju-kpop-route.jpg",
])

export const EXPECTED_ROUTE_FILES = Object.freeze([
  "api/ondo/venues/[venueId]/route.ts",
  "layout.tsx",
  "ondo-b/page.tsx",
  "page.tsx",
])

export const BLOCKED_HTTP_PATHS = Object.freeze([
  // Archived source assets are retained in Git, but never publicly shipped.
  "/brand/ktour-id-lockup-transparent.png",
  "/brand/ktour-id-lockup.png",
  "/brand/ktour-id-logo-source.png",
  "/brand/ktour-id-mark-180.png",
  "/brand/ktour-id-mark-192.png",
  "/brand/ktour-id-mark-32.png",
  "/brand/ktour-id-mark-512.png",
  "/brand/ktour-id-mark-64.png",
  "/brand/ktour-id-mark.png",
  "/brand/ktour-id-wordmark.png",
  "/brand/ondo-lockup.svg",
  "/brand/ondo-mark.svg",
  "/brand/ondo-mark-inverse.svg",
  "/brand/ondo-mark-micro-24.svg",
  "/og-ktour-food-v1.png",
  "/ai",
  "/alerts",
  "/api/ask",
  "/api/chat",
  "/architecture",
  "/ask",
  "/benefits",
  "/connect",
  "/connect/chat",
  "/demo",
  "/evidence",
  "/explore",
  "/help",
  "/journey",
  "/ondo",
  "/onboarding",
  "/orders/legacy",
  "/partner/settlements",
  "/partner/verify",
  "/pass",
  "/present",
  "/profile",
  "/services",
  "/wallet",
  "/og-modern-atlas.png",
  "/og-ondo.png",
])

// Keep retired prototype clusters out of the standalone artifact without
// treating required journey truth (including simulated OpenDID/eKYC) as a
// failure. Retired overlay symbols stay blocked below; current Payment KYC is
// a required, provider-neutral B axis and is proven by the positive source list.
export const LEGACY_ARTIFACT_PATH = /(^|\/)(?:(?:demo|fixtures?|mock|partner|rewards|trust|wallet)(?:[./_-]|\/|$)|profile(?:\/|$))/i

export const LEGACY_ARTIFACT_TEXT = Object.freeze([
  /"simulation"\s*:\s*null/i,
  /\b(?:reward|rewards)\b/i,
  /demo-journey/i,
  /mock-data/i,
  /WalletProvider|chainProvider|blockchain/i,
  // Retire the legacy overlay identifier without rejecting the current
  // MapLibre source/layer ids (`ondo-after19-lens` and eligible-*).
  /ondo-after19-layer/i,
  /Checkout simulation/i,
  /CheckoutOverlay|ChatOverlay|RewardsEntry/i,
  /결제 시뮬레이션/i,
  /Labs · (?:Local|로컬)/i,
  /CheckoutOverlay|ChatOverlay|RewardsEntry|\bLabsEntry\b/,
  /k-tour-id\.wallet/i,
  /(?:^|["'`])\/(?:demo|wallet|ondo|ask|chat|connect|partner|profile|services|pass|present|journey|benefits|architecture|evidence)(?:[/?"'`]|$)/m,
])

export const FORBIDDEN_QA_ARTIFACT_TEXT = Object.freeze([
  /__ONDO_B_QA__/,
  /ondo\.qa\.controls\.v1/,
  /ondo\.qa\.scenario\.v1/,
  /NEXT_PUBLIC_ONDO_QA_CONTROLS/,
])
