import { expect, test } from "@playwright/test"
import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { JEJU_EDITORIAL_PLACES, JEJU_EDITORIAL_SEEDS, JEJU_EDITORIAL_TEMPERATURE } from "../../features/ondo/pulse-b/japan-first-pulse-model-b"

const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8")

test("JP-MAP-FIRST-001 Korea overview owns Seoul, Busan, and truthful Jeju anchors", () => {
  const map = source("features/ondo/map/map-entry-b.tsx")

  expect(map).toContain('type CityId = "seoul" | "busan" | "jeju"')
  expect(map).toContain('data-testid="ondo-b-korea-atlas"')
  expect(map).toContain('id: "jeju"')
  expect(map).toContain('truthKind: "editorial-region"')
  expect(map).toContain("editorialCount: JEJU_EDITORIAL_PLACES.length")
  expect(map).toContain('data-editorial-candidate-count={cityNode.id === "jeju" ? JEJU_EDITORIAL_SEEDS.length - JEJU_EDITORIAL_PLACES.length : undefined}')
  expect(map).toContain('data-signal-state={cityNode.signalState}')
  expect(map).toContain('signalState: JEJU_EDITORIAL_TEMPERATURE.level')
  expect(map).toContain('data-label-side={cityNode.labelOffset.x < 0 ? "left" : "right"}')
  expect(map).toContain("cityNodes.map")
  expect(map).toContain('<i aria-hidden="true" />')
  expect(map).toContain('data-atlas-pin="true"')
  expect(map).toContain('data-testid="ondo-b-atlas-plot"')
  expect(map).toContain("KOREA_ATLAS_CITY_COORDINATES")
  expect(map).toContain('data-atlas-latitude={cityNode.coordinates.latitude}')
  expect(map).toContain('data-atlas-longitude={cityNode.coordinates.longitude}')
  expect(map).not.toContain("KOREA_ATLAS_LANDMASS_PATHS")
  expect(map).not.toContain("data-atlas-x")
  expect(map).not.toContain("data-atlas-y")
  expect(map).not.toContain("data-atlas-stop")
  expect(map).toContain('instance.project([coordinates.longitude, coordinates.latitude])')
  expect(map).toContain('cityNode.dataset.mapProjected = "true"')
  expect(map).not.toContain("data-region-kind-label")
  expect(map).not.toContain('Sparkles size={18}')
  expect(map).not.toContain('className={`${styles.cityNode} ${styles.jejuNode}`}')
})

test("JP-MAP-FIRST-001A overview and city share one persistent live map canvas", () => {
  const map = source("features/ondo/map/map-entry-b.tsx")
  const css = source("features/ondo/map/map-b.module.css")
  const globals = source("app/globals.css")

  expect(map.match(/new Map\(/g)).toHaveLength(1)
  expect(map).toContain('className={`${styles.map} ${styles.persistentMap}`}')
  expect(map).toContain('id: "ondo-overview-route"')
  expect(map).toContain('id: "ondo-korea-coastline"')
  expect(map).toContain('id: "ondo-overview-city-aura"')
  expect(map).toContain("const CITY_FOCUS_DURATION_MS = 340")
  expect(map).toContain("const CITY_FOCUS_SETTLE_GUARD_MS = 400")
  expect(map).toContain("const NATION_RETURN_DURATION_MS = 440")
  expect(map).toContain("map.easeTo({")
  expect(map).toContain("duration: CITY_FOCUS_DURATION_MS")
  expect(map).toContain("map.stop()")
  expect(map).toContain("dataset.cityFocusStartDelay")
  expect(map).toContain('data-map-attempt={mapAttempt}')
  expect(map).not.toContain("map.flyTo({")
  expect(map).not.toContain("duration: 820")
  expect(map).not.toContain("curve: 1.18")
  expect(map).not.toContain('toDataURL("image/png")')
  expect(map).not.toContain("preserveDrawingBuffer")
  expect(map).not.toContain("entryMapSnapshot")
  expect(map).not.toContain("NationBasemap")
  expect(map).toContain('window.matchMedia("(prefers-reduced-motion: reduce)").matches')
  expect(map).not.toContain("transitionDocument.startViewTransition")
  expect(css).not.toContain("view-transition-name: ondo-map-surface")
  expect(globals).not.toContain("::view-transition-old(ondo-map-surface)")
  expect(css).toContain('.koreaAtlas[data-departing-city]')
  expect(css).toContain('.persistentMap[data-map-mode="nation"]')
  expect(css).toContain("@media (prefers-reduced-motion: reduce)")
})

test("JP-MAP-FIRST-002 city entry defaults to map without measuring or short-landscape list flash", () => {
  const map = source("features/ondo/map/map-entry-b.tsx")
  const history = source("features/ondo/map/b-discovery-history.ts")

  expect(history).toContain('export type BDiscoveryCity = "seoul" | "busan" | "jeju"')
  expect(history).toContain('value === "jeju"')
  expect(history).toContain("view: requestedView")
  // COLLECTION-HISTORY-001/005 exercise both ordinary-query preservation and
  // the empty city parent beneath a directly linked collection at runtime.
  expect(history).toContain('const requestedQuery = queryValue(url.searchParams.get("q"))')
  expect(history).toContain('query: requestedCollection ? "" : requestedQuery')
  expect(history).toContain("category: requestedCategory")
  expect(history).toContain('editorialCategory: requestedCity === "jeju" ? requestedEditorialCategory : "all"')
  expect(map).toContain('mapLayoutMode === "ultra-short" ? "list" : view')
  expect(map).not.toContain('mapLayoutMode === "ultra-short" || mapLayoutMode === "measuring" ? "list" : view')
  expect(map).toContain('height < 260')
  expect(map).not.toContain('height < 400')
})

test("JP-MAP-FIRST-003 Japan stories are a contextual map layer, never a Nation feed", () => {
  const map = source("features/ondo/map/map-entry-b.tsx")
  const discovery = source("features/ondo/map/japan-first-discovery-b.tsx")
  const nationDirectory = map.slice(map.indexOf("function NationDirectory"), map.indexOf("function toFeatureCollection"))

  expect(map).toContain('<JapanFirstDiscoveryB locale={locale} city={city}')
  expect(map).toContain('presentation={effectiveView === "list" || mapState === "error" ? "list" : "map"}')
  expect(map).toContain('onOpenChange={setEditorialOpen}')
  expect(map).toContain('inert={editorialOpen ? true : undefined}')
  expect(map).toContain('aria-hidden={editorialOpen || effectiveView !== "map" ? true : undefined}')
  expect(nationDirectory).not.toContain("<JapanFirstDiscoveryB")
  expect(discovery).toContain('city: "seoul" | "jeju"')
  expect(discovery).toContain('data-truth-kind="editorial-collection"')
  expect(discovery).toContain("item.cityIds.includes(city)")
})

test("JP-MAP-FIRST-004 only place-page-verified Jeju research becomes an editorial point", () => {
  expect(JEJU_EDITORIAL_SEEDS).toHaveLength(10)
  expect(JEJU_EDITORIAL_SEEDS.every((item) => item.canonicalVenueId === null)).toBe(true)
  expect(JEJU_EDITORIAL_SEEDS.every((item) => item.officialRecordCount === null)).toBe(true)
  expect(JEJU_EDITORIAL_PLACES).toHaveLength(8)
  expect(JEJU_EDITORIAL_PLACES.every((item) => item.kind === "editorial-place" && item.placeEdgeVerification === "verified")).toBe(true)
  expect(JEJU_EDITORIAL_PLACES.every((item) => item.officialRecord === false && item.pulseEligible === false)).toBe(true)
  expect(JEJU_EDITORIAL_TEMPERATURE).toMatchObject({ level: "limited", score: null, mode: "editorial-coverage", model: "editorial-unscored", pulseEligible: false, officialRecord: false })
  expect(JEJU_EDITORIAL_PLACES.every((item) => item.location.coordinateSource === "VISITKOREA_EMBEDDED_MAP" && item.location.verifiedAt === "2026-08-28")).toBe(true)
  expect(JEJU_EDITORIAL_SEEDS.filter((item) => item.kind === "editorial-place-candidate").map((item) => item.id)).toEqual(["jeju-tamura", "jeju-sogil-byeolha"])
  expect(JEJU_EDITORIAL_SEEDS.filter((item) => item.kind === "editorial-place-candidate").every((item) => !("location" in item))).toBe(true)

  const map = source("features/ondo/map/map-entry-b.tsx")
  const editorialModel = source("features/ondo/pulse-b/japan-first-pulse-model-b.ts")
  const css = source("features/ondo/map/map-b.module.css")
  expect(map).toContain("function toTemperatureFeatureCollection")
  expect(map).toContain('entryKind: "editorial" as const')
  expect(map).toContain('signalKind: "verified-editorial"')
  expect(map).toContain('function editorialCoverageVisualRank(place: EditorialPlaceB)')
  expect(editorialModel).toContain('export function jejuEditorialCoverageIntensity(place: EditorialPlaceB)')
  expect(map).not.toContain('function editorialCoverageLevel(place: EditorialPlaceB)')
  expect(map).toContain('EDITORIAL_COVERAGE_VISUAL_RANK[jejuEditorialCoverageIntensity(place)]')
  expect(map).toContain('pulseLevel: JEJU_EDITORIAL_TEMPERATURE.level')
  expect(map).toContain('pulseRank: PULSE_RANK[JEJU_EDITORIAL_TEMPERATURE.level]')
  expect(map).toContain('signal: id === "seoul" ? "active" : id === "busan" ? "growing" : "editorial"')
  expect(map).toContain('data-pulse-priority={JEJU_EDITORIAL_TEMPERATURE.level}')
  expect(map).toContain('data-coverage-intensity={coverageIntensity}')
  expect(map).toContain('editorialPlaces.map((place) => <li key={place.id}>{`${place.name[locale]} · ${jejuEditorialCoverageSummary(place, locale, TEMPERATURE_NAME[locale])}`}</li>)')
  expect(map).toContain('data-temperature-shell="city-map"')
  expect(map).toContain('data-editorial-category={item}')
  expect(map).toContain('id: "ondo-temperature-field"')
  expect(map).toContain('id: "ondo-selected-pulse-capsule"')
  expect(map).not.toContain('id: "ondo-editorial-temperature-aura"')
  expect(map).not.toContain('id: "ondo-editorial-points"')
  expect(map).toContain('data-editorial-temperature-mode={city === "jeju" ? JEJU_EDITORIAL_TEMPERATURE.mode : undefined}')
  expect(map).toContain('data-editorial-temperature-score={city === "jeju" ? "none" : undefined}')
  expect(map).toContain('data-editorial-temperature-key={city === "jeju" ? "unscored" : undefined}')
  expect(map).toContain('data-pulse-key-presentation={city === "jeju" ? "compact-coverage" : "compact-gradient"}')
  expect(map).toContain('["==", ["get", "signalKind"], "verified-editorial"], EDITORIAL_COVERAGE_COLOR')
  expect(map).toContain('city === "jeju" ? EDITORIAL_COVERAGE_HEAT_COLOR')
  expect(css).toContain('.mapKey[data-editorial-temperature-key="unscored"] .pulseScale > i')
  expect(css).toContain('.venueList li.editorialListItem {')
  expect(css).toContain('--list-pulse: #d9bf73;')
  expect(map).toContain('data-temperature-visual-grammar="shared-field-aura-core-scale-selection-capsule"')
  expect(map).toContain('data-temperature-model={city === "jeju" ? JEJU_EDITORIAL_TEMPERATURE.model : "curated-scored"}')
  expect(map).toContain('data-editorial-point-count={city === "jeju" ? JEJU_EDITORIAL_PLACES.length : undefined}')

  const detail = source("features/ondo/place/editorial-place-overlay-b.tsx")
  expect(detail).toContain('data-pulse-level={JEJU_EDITORIAL_TEMPERATURE.level}')
  expect(detail).toContain('data-coverage-intensity={coverageIntensity}')
  expect(detail).toContain('data-temperature-model={JEJU_EDITORIAL_TEMPERATURE.model}')
  expect(detail).toContain('data-editorial-temperature-mode={JEJU_EDITORIAL_TEMPERATURE.mode}')
  expect(detail).toContain('jejuEditorialCoverageSummary(activePlace, locale, copy.temperature)')
})

test("JP-MAP-FIRST-005 atlas hover never replaces geographic translation", () => {
  const css = source("features/ondo/map/map-b.module.css")
  const shell = source("features/ondo/app/ondo-shell.module.css")

  expect(css).toMatch(/\.koreaAtlas \.cityNode:hover,[\s\S]*transform:\s*translate\(-50%, -50%\)/)
  expect(css).toContain('.cityNode[data-label-side="left"] span')
  expect(shell).toContain(':not([data-atlas-pin="true"]):hover')
  expect(shell).toContain('button[data-atlas-pin="true"] { transform: translate(-50%, -50%) !important; }')
})
