import { test, expect, type Page } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"

const route = "/ondo-b/labs/discovery"
async function start(page: Page) {
  await page.goto(route)
  await expect(page.getByTestId("discovery-preview")).toBeVisible()
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-ready", "true")
  // Dev build indicator is not product UI and may occlude bottom controls.
  await page.addStyleTag({ content: "nextjs-portal { display: none !important; }" })
}
async function search(page: Page, text: string) {
  const field = page.getByRole("searchbox").or(page.getByRole("textbox", { name: /Hot/ }))
  await field.fill(text)
  await field.press("Enter")
}

test("preview: both story journeys use the same geographic pin/card IDs and exact works", async ({ page }) => {
  await start(page)
  await page.getByTestId("story-sesame").click()
  await expect(page.locator("[data-place-card]")).toHaveCount(1)
  await expect(page.locator("[data-place-card]")).toHaveAttribute("data-place-card", "lab-seoul-jungbu-market")
  await expect(page.locator("button[data-place-id='lab-seoul-jungbu-market']")).toBeVisible({ timeout: 20000 })
  await page.getByRole("button", { name: "중부시장 · 장소 보기" }).click()
  await expect(page.getByRole("dialog")).toContainText("참기름 이야기가 시작된 시장")
  await page.getByRole("dialog").getByRole("button", { name: "지도에서 보기" }).click()
  await expect(page.locator("[data-place-card][data-selected=true]")).toHaveAttribute("data-place-card", "lab-seoul-jungbu-market")
  await page.getByRole("button", { name: "이전 탐색으로" }).first().click()
  await page.getByTestId("story-screen").click()
  await expect(page.getByRole("combobox", { name: "도시", exact: true })).toHaveValue("jeju")
  await expect(page.locator("[data-place-card]")).toHaveCount(2)
  await expect(page.locator("[data-place-card='jeju-seongsan-ilchulbong']")).toContainText("폭싹")
  await expect(page.locator("[data-place-card='jeju-gwangchigi-beach']")).toContainText("삼달리")
  await page.getByRole("button", { name: "이전 탐색으로" }).first().click()
  await expect(page.getByRole("combobox", { name: "도시", exact: true })).toHaveValue("seoul")
})

test("preview: Hot/Cool replace story scope and respect city/filter; literal names stay literal", async ({ page }) => {
  await start(page)
  await page.getByTestId("story-sesame").click()
  await search(page, " HOT ")
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "hot")
  await expect(page.locator("[data-place-card]")).toHaveCount(3)
  await page.getByRole("button", { name: "카페", exact: true }).click()
  await expect(page.locator("[data-place-card]")).toHaveCount(2)
  await search(page, "Cool")
  await expect(page.locator("[data-place-card]")).toHaveCount(1)
  await expect(page.locator("[data-place-card]")).toContainText("학림다방")
  await page.getByRole("combobox", { name: "도시", exact: true }).selectOption("jeju")
  await expect(page.locator("[data-place-card]")).toHaveCount(0)
  await expect(page.getByTestId("discovery-tray")).toContainText("0곳")
  await expect(page.getByTestId("discovery-tray")).toContainText("아직 맞는 장소가 없어요")
  await search(page, "Hotdog")
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "search")
  await expect(page.locator("[data-place-card]")).toHaveCount(0)
})

test("preview: map selection, horizontal rail, local save and detail return stay in sync", async ({ page }) => {
  await start(page)
  await page.getByRole("button", { name: "Hot", exact: true }).click()
  await expect(page.locator("button[data-place-id='research-seoul-geumdwaeji-sikdang']")).toBeVisible({ timeout: 20000 })
  await page.locator("button[data-place-id='research-seoul-geumdwaeji-sikdang']").click()
  await expect(page.locator("[data-place-card][data-selected=true]")).toHaveAttribute("data-place-card", "research-seoul-geumdwaeji-sikdang")
  await page.getByRole("button", { name: "금돼지식당 · 장소 보기" }).click()
  await page.getByRole("dialog").getByRole("button", { name: "저장", exact: true }).click()
  await expect(page.getByRole("dialog").getByRole("button", { name: "저장됨", exact: true })).toHaveAttribute("aria-pressed", "true")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByRole("button", { name: "금돼지식당 · 장소 보기" })).toBeFocused()
  await page.getByRole("button", { name: "저장한 장소", exact: true }).click()
  await expect(page.locator("[data-place-card]")).toHaveCount(1)
  await expect(page.locator("[data-place-card]")).toContainText("금돼지식당")
  await page.getByRole("button", { name: "이전 탐색으로" }).first().click()
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "hot")
  await expect(page.locator("[data-place-card][data-selected=true]")).toHaveAttribute("data-place-card", "research-seoul-geumdwaeji-sikdang")
  await page.reload()
  await page.getByRole("button", { name: "저장한 장소", exact: true }).click()
  await expect(page.locator("[data-place-card]")).toHaveCount(0)
})

test("preview: map outage and failed images keep place actions usable", async ({ page }) => {
  await page.route("https://tiles.openfreemap.org/**", r => r.abort())
  await page.route("**/media/venues/**", r => r.abort())
  await start(page)
  await page.getByRole("button", { name: "Hot", exact: true }).click()
  await expect(page.getByRole("status").filter({ hasText: "지도를 불러오지 못했어요" })).toBeVisible({ timeout: 20000 })
  await page.getByRole("button", { name: "어니언 안국 · 장소 보기" }).click()
  await expect(page.getByRole("dialog")).toContainText("어니언 안국")
  await page.getByRole("dialog").getByRole("button", { name: "저장", exact: true }).click()
  await expect(page.getByRole("dialog")).toContainText("저장됨")
})

for (const size of [{ width: 320, height: 720 }, { width: 390, height: 844 }, { width: 430, height: 932 }, { width: 844, height: 390 }, { width: 1440, height: 1000 }]) {
  test(`preview: mobile composition / ${size.width}x${size.height}`, async ({ page }, testInfo) => {
    await page.setViewportSize(size)
    await start(page)
    await page.getByRole("button", { name: "Hot", exact: true }).click()
    await expect(page.locator("[data-place-card]")).toHaveCount(3)
    await expect(page.getByTestId("discovery-map")).toHaveAttribute("data-rendered", "true", { timeout: 20000 })
    await expect(page.locator("button[data-place-id]")).toHaveCount(3)
    const geometry = await page.evaluate(() => {
      const root = document.querySelector("main")!
      const header = root.querySelector("header")!.getBoundingClientRect()
      const tray = document.querySelector('[data-testid="discovery-tray"]')!.getBoundingClientRect()
      return { overflow: document.documentElement.scrollWidth - innerWidth, freeHeight: tray.top - header.bottom, freeWidth: innerWidth - tray.right, height: innerHeight, width: innerWidth }
    })
    expect(geometry.overflow).toBeLessThanOrEqual(1)
    if (size.width < 600) expect(geometry.freeHeight).toBeGreaterThanOrEqual(size.height * .5 - 2)
    else expect(geometry.freeWidth).toBeGreaterThanOrEqual(size.width * .5)
    await page.screenshot({ path: testInfo.outputPath("hot.png") })
    await page.getByRole("button", { name: /어니언 안국 · 장소 보기/ }).click()
    const dialog = page.getByRole("dialog")
    await expect(dialog.getByRole("button", { name: "지도에서 보기" })).toBeInViewport()
    const violations = (await new AxeBuilder({ page }).include('[data-testid="discovery-preview"]').analyze()).violations.filter(v => v.impact === "critical" || v.impact === "serious")
    expect(violations.map(v => `${v.id}: ${v.nodes.map(n => n.target).join(",")}`)).toEqual([])
    await page.screenshot({ path: testInfo.outputPath("place.png") })
  })
}

test("preview: Japanese dark mode and reduced motion", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.emulateMedia({ colorScheme: "dark", reducedMotion: "reduce" })
  await start(page)
  await page.getByRole("button", { name: "Change language to English" }).click()
  await page.getByRole("button", { name: "日本語に変更" }).click()
  await page.getByTestId("story-screen").click()
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-theme", "dark")
  await expect(page.getByTestId("discovery-tray")).toContainText("ドラマの済州へ")
  await page.getByRole("button", { name: "城山日出峰 · 場所を見る" }).click()
  await expect(page.getByRole("dialog")).toContainText("『おつかれさま』の風景")
  await expect(page.getByRole("dialog").getByRole("button", { name: "地図で見る" })).toBeInViewport()
  const violations = (await new AxeBuilder({ page }).include('[data-testid="discovery-preview"]').analyze()).violations.filter(v => v.impact === "critical" || v.impact === "serious")
  expect(violations.map(v => v.id)).toEqual([])
})

test("preview: native Back/Forward and rotation preserve the selected stop", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await start(page)
  await page.getByRole("button", { name: "Cool", exact: true }).click()
  await page.getByRole("combobox", { name: "장소 종류", exact: true }).selectOption("food")
  const pin = page.locator("button[data-place-id='research-seoul-okdongsik']")
  await expect(pin).toBeVisible({ timeout: 20000 })
  await pin.click()
  await expect(page.locator("[data-place-card][data-selected=true]")).toHaveAttribute("data-place-card", "research-seoul-okdongsik")
  await page.mouse.move(220, 220)
  await page.mouse.down()
  await page.mouse.move(195, 242, { steps: 10 })
  await page.mouse.up()
  await expect.poll(() => page.evaluate(() => Boolean(window.history.state?.discoveryPreview?.snapshot?.camera))).toBe(true)
  // Wait for drag inertia before comparing the entire transform on native return.
  await page.waitForTimeout(600)
  const before = await pin.boundingBox()
  await page.goBack()
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "explore")
  await page.goForward()
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "cool")
  await expect(page.locator("[data-place-card][data-selected=true]")).toHaveAttribute("data-place-card", "research-seoul-okdongsik")
  await expect.poll(async () => {
    const after = await pin.boundingBox()
    return Math.abs(after!.x - before!.x) + Math.abs(after!.y - before!.y)
  }).toBeLessThan(2)
  await page.setViewportSize({ width: 844, height: 390 })
  await expect.poll(() => pin.evaluate(el => {
    const box = el.getBoundingClientRect()
    return el.contains(document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2))
  })).toBe(true)
  await page.getByRole("button", { name: "옥동식 · 장소 보기" }).click()
  await page.goBack()
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "cool")
})

test("preview: short Japanese layout keeps city recovery and story places reachable", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await start(page)
  await page.getByRole("button", { name: "Change language to English" }).click()
  await page.getByRole("button", { name: "日本語に変更" }).click()
  await page.getByRole("button", { name: "Cool", exact: true }).click()
  await page.getByRole("combobox", { name: "Place type", exact: true }).selectOption("cafe")
  await search(page, "coffee")
  await page.getByRole("combobox", { name: "City", exact: true }).selectOption("jeju")
  await page.getByTestId("story-screen").click()
  await expect(page.locator("[data-place-card]")).toHaveCount(2)
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(569)
  await expect(page.getByRole("button", { name: "ローカル試作", exact: true })).toBeInViewport()
  await page.getByRole("button", { name: "ローカル試作", exact: true }).click()
  await page.getByRole("dialog").getByRole("combobox", { name: "City" }).selectOption("seoul")
  await expect(page.getByRole("dialog")).toHaveCount(0)
  await expect(page.getByTestId("discovery-preview")).toHaveAttribute("data-mode", "explore")
  await page.getByRole("button", { name: "Hot", exact: true }).click()
  await expect(page.locator("[data-place-card]")).toHaveCount(3)
})
