import { expect, test, type Locator, type Page } from "@playwright/test"

test.describe.configure({ timeout: 60_000 })
const errors = new WeakMap<Page, string[]>()
test.beforeEach(({ page }) => {
  const seen: string[] = []
  errors.set(page, seen)
  page.on("pageerror", error => seen.push(error.message))
})
test.afterEach(({ page }) => { expect(errors.get(page) ?? []).toEqual([]) })

async function usable(action: Locator, height: number) {
  const box = await action.boundingBox()
  expect(box).not.toBeNull()
  expect(box!.height).toBeGreaterThanOrEqual(52)
  expect(box!.y).toBeGreaterThanOrEqual(0)
  expect(box!.y + box!.height).toBeLessThanOrEqual(height)
  expect(await action.evaluate(node => {
    const rect = node.getBoundingClientRect()
    return node.contains(document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2))
  })).toBe(true)
}

for (const locale of ["en", "ja"] as const) test(`UX16 research detail shares in-body service rows and an exact return at 320px ${locale}`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 320, height: 480 })
  await page.addInitScript(locale => localStorage.setItem("ondo-b.device.v1", JSON.stringify({ locale, appearancePreference: "dark", onboarding: "ONB-COMPLETE" })), locale)
  await page.goto("/?city=seoul&view=list", { waitUntil: "domcontentloaded" })
  await page.locator('[data-research-id="research-seoul-zest"]').first().click()
  const detail = page.getByTestId("researched-food-detail")
  const sheet = page.getByTestId("ondo-sheet").filter({ has: detail })
  const footer = sheet.locator("[data-sheet-footer]")
  const pay = detail.getByTestId("place-offer-open")
  const map = footer.getByTestId("research-on-map")
  await expect(page.getByTestId("place-offer-open")).toHaveCount(1)
  await expect(footer.getByTestId("place-offer-open")).toHaveCount(0)
  await expect(detail.getByTestId("place-detail-actions")).toHaveAttribute("data-service-place-id", "research-seoul-zest")
  await expect(detail.getByTestId("place-service-actions")).toHaveAttribute("data-service-layout", "rows")
  await pay.scrollIntoViewIfNeeded()
  await usable(pay, 480)
  await usable(map, 480)
  await expect(detail.getByTestId("place-reservation-open")).toHaveCount(1)
  await expect(footer.getByTestId("research-directions")).toHaveAttribute("target", "_blank")
  await detail.getByTestId("research-place-source").locator("summary").click()
  await pay.focus()
  await page.keyboard.press("Tab")
  await expect(detail.getByTestId("place-reservation-open")).toBeFocused()
  await pay.focus()
  const scroll = sheet.locator("[data-sheet-scroll-owner]")
  const before = await scroll.evaluate(node => node.scrollTop)
  await pay.click()
  await expect(page.getByTestId("commerce-place-context")).toHaveAttribute("data-venue-id", "research-seoul-zest")
  await page.getByTestId("commerce-origin-return").click()
  await expect(detail).toHaveAttribute("data-research-id", "research-seoul-zest")
  await expect(detail.getByTestId("research-place-source")).toHaveAttribute("open", "")
  await expect.poll(() => scroll.evaluate(node => node.scrollTop)).toBeCloseTo(before, 0)
  await expect(pay).toBeFocused()
  await page.waitForTimeout(400)
  await expect(pay).toBeFocused()
  await usable(pay, 480)
  expect(await page.locator("html").evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath(`research-footer-${locale}.png`), scale: "css" })
  // A new payment sheet owns focus; an old return must not reclaim it.
  await pay.click()
  await expect(page.getByTestId("commerce-origin-return")).toBeFocused()
  await page.waitForTimeout(400)
  await expect(page.getByTestId("commerce-origin-return")).toBeFocused()
})

test("UX16 a content-only place retains map and directions without gaining payment", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/?city=seoul&view=list", { waitUntil: "domcontentloaded" })
  await page.locator('[data-research-id="research-seoul-hakrim-dabang"]').first().click()
  const detail = page.getByTestId("researched-food-detail")
  const sheet = page.getByTestId("ondo-sheet").filter({ has: detail })
  const footer = sheet.locator("[data-sheet-footer]")
  await expect(sheet.getByTestId("place-offer-open")).toHaveCount(0)
  await expect(sheet.getByTestId("place-service-actions")).toHaveCount(0)
  await expect(footer.getByTestId("research-on-map")).toHaveAttribute("data-visual-priority", "primary")
  await expect(footer.getByTestId("research-directions")).toHaveAttribute("rel", "noopener noreferrer")
  await usable(footer.getByTestId("research-on-map"), 844)
  await usable(footer.getByTestId("research-directions"), 844)
  await page.screenshot({ path: testInfo.outputPath("content-only-place.png"), scale: "css" })
})

test("UX16 pulse uses the same prepared frame with legible and motion-free counts", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.emulateMedia({ reducedMotion: "reduce" })
  await page.addInitScript(() => localStorage.setItem("ondo-b.device.v1", JSON.stringify({ locale: "ja", appearancePreference: "dark", onboarding: "ONB-COMPLETE" })))
  await page.goto("/?venueId=mois-0021cd596bc5b2a922ad", { waitUntil: "domcontentloaded" })
  const pulse = page.getByTestId("canonical-place-peek").getByTestId("canonical-place-pulse")
  await expect(pulse).toHaveAttribute("data-origin", "PREPARED_ILLUSTRATION")
  await expect(pulse).toHaveAttribute("data-sample-running", "false")
  const values = pulse.getByTestId("sample-traveler-contributions")
  for (const item of await values.locator("small").all()) {
    expect(await item.evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(11)
  }
  expect(await values.locator("b").evaluateAll(nodes => nodes.every(node => getComputedStyle(node).animationName === "none"))).toBe(true)
  const before = await pulse.getAttribute("data-sample-minute")
  // Close and reselect to test persistence across the preview lifetime, then
  // reselect through the map's accessible place list. Switching to the main
  // list would unmount this map timeline, so it cannot prove frame continuity.
  await page.keyboard.press("Escape")
  await expect(page.getByTestId("canonical-place-peek")).toHaveCount(0)
  await page.getByTestId("ondo-temperature-play").click()
  const nextMinute = await page.getByTestId("ondo-temperature-timeline").getAttribute("data-minute")
  await page.getByTestId("ondo-b-map-key-details").locator(":scope > summary").click()
  await page.getByTestId("ondo-b-pulse-methodology").locator(":scope > summary").click()
  await page.getByTestId("ondo-b-map-pulse-places").locator('button[data-venue-id="mois-0021cd596bc5b2a922ad"]').click()
  await expect(pulse).not.toHaveAttribute("data-sample-minute", before!)
  await expect(pulse).toHaveAttribute("data-sample-minute", nextMinute!)
  await expect(pulse).toHaveAttribute("data-sample-running", "false")
  expect(await values.locator("b").evaluateAll(nodes => nodes.every(node => getComputedStyle(node).animationName === "none"))).toBe(true)
  expect(await page.locator("html").evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath("pulse-ja320-reduced-motion.png"), scale: "css" })
})
